[http]
host = "0.0.0.0"
port = 2048

# Defines TLS configuration options. Private keys can be hard coded or loaded from a file.
[tls]
tls-versions = ["1.1", "1.2", "1.3"]
private-key = "..."
public-key = "..."

# Defines CORS configuration
[cors]
allow-origins = ["https://cdn.example.com", "http://cdn.example.com"]
allow-methods = ["HEAD", "GET", "OPTIONS", "DELETE"]
allow-headers = ["Authorization", "Accept", "Cache-Control"]
allow-credentials = true

[cache-control]
# Either "cache" or "no-cache"
default-policy = "cache"
# Default "max-age" property if the policy is set to "cache"
default-max-age = 3_600

# Defines settings that determine authentication behavior
[access-control]
# Allow the creation of scoped access tokens
enable-access-tokens = true
# Disables authenticaiton checks for any connections made from localhost IP
# addresses (127.0.0.0/16)
enable-localhost-auth-bypass = true

# Defines either an IP whitelist or an IP blacklist, but not both
[ip-filter]
# Whitelist of IP addresses or subnets that are allowed past the IP filter
whitelist = ["192.168.1.0/24", "192.168.2.4"]
# Blacklist of IP addresses or subnets that are not allowed past the IP filter
blacklist = ["192.168.3.0/24"]

# Defines either a Content-Type whitelist or a Content-Type blacklist, but not both
[content-types]
# Content types that are allowed to be stored
whitelist = ['text/html', 'application/javascript']
# Content types that are not allowed to be stored
blacklist = ['video/mp4']

# Defines options for configuring default rate limits
[rate-limiting]
default-period = "30s"
default-burst-size = 10
